services:
  app:
    container_name: laravel
    build:
      context: laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel/:/var/www
    depends_on:
      - db
    networks:
      - app

  horizon:
    container_name: horizon
    build:
      context: laravel
      dockerfile: Dockerfile-queue
    volumes:
      - ./laravel/:/var/www
    depends_on:
      - db
    networks:
      - app

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #       MYSQL_DATABASE: ${DB_DATABASE}
  #       MYSQL_USER: ${DB_USERNAME}
  #       MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #       - ./docker/data:/var/lib/mysql
  #   ports:
  #       - ${DB_PORT}:${DB_PORT}
  #   networks:
  #       - app

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./docker/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./laravel/:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOST}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
        - "15672:15672"
        - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    restart: always
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    networks:
      - app

  redis:
      image: redis:alpine
      container_name: redis
      restart: unless-stopped
      volumes:
      - ./docker/redis:/data
      ports:
        - ${REDIS_PORT}:${REDIS_PORT}
      networks:
      - app

networks:
    app:
        name: app
